### ISSUE TITLE
Joinleave.py มีไม้เอกหน้าชื่อ file

### ISSUE THREAD

**Issue by ponmak** [tunwit/Cs-Discord-bot#3]
![IMG_0119](https://github.com/user-attachments/assets/21271fcb-e6d5-48ef-9537-3ea63a8adf71)
[joinleave.py](https://github.com/tunwit/Cs-Discord-bot/blob/main/cogs/%E0%B9%88joinleave.py) แก้ด้วยจั้บ

**Comment by tunwit** [comment]
Fixed
